# Generated by Django 5.2.1 on 2025-05-16 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=10)),
                ('floor_number', models.PositiveIntegerField()),
                ('total_bed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=15)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
