# Generated by Django 5.2.1 on 2025-05-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='rooms_room',
        ),
    ]
