# Generated by Django 5.2.1 on 2025-05-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='rooms_rooms',
        ),
    ]
